services:
  api:
    build: .
    volumes:
      - ./:/app
    environment:
      - AUTH_KEYS=YOUR_HTTP_AUTHORIZATION_KEYS_SEPARATED_BY_COMMA
      - LLM_MODEL=qwen-plus
      - BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - API_KEY=YOUR_API_KEY
    ports:
      - "8000:8000"